Remove deprecated 'bottle :unneeded'
With the newest homebrew version I was not able to install your amazing tool.
The error message was
```
Error: Invalid formula: /opt/homebrew/Library/Taps/danielthank/homebrew-tap/assume-role.rb
assume-role: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the danielthank/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/danielthank/homebrew-tap/assume-role.rb:6

Error: Cannot tap danielthank/tap: invalid syntax in tap!
```
After applying the proposed changes locally, everything works perfectly.
Source of the solution I found here: https://github.com/Azure/homebrew-functions/pull/90/files

(I really don't know much about homebrew and how the taps work in general, so I am just proposing what was working. No clue, if there needs to be some backwards compatibility or something)

Thank you for having a look!